"""
Render self-contained Kaggle notebook to train and benchmark Arm H (BARTpho-syllable-base)
on the 300,000-pair clean Pilot Dataset.

Fair comparison design:
- Cùng dataset: data/base_v3_pilot (300K pairs)
- Cùng số bước: 10,000 steps
- Cùng 5 frozen eval suites (3,100 queries) + 18 zero-click cases
- Cùng metric: Mean Accuracy, per-suite breakdown, latency CPU INT8
- Điểm khác duy nhất: BARTpho-syllable-base pretrained (vinai/bartpho-syllable-base, 132M)
"""

import json
from pathlib import Path


ZERO_CLICK_CASES_CODE = """\
ZERO_CLICK_CASES = [
    ("cau vuot song than",                         "cầu vượt sóng thần"),
    ("cho ba chieu",                               "chợ bà chiểu"),
    ("nga 4 hang xanh",                            "ngã 4 hàng xanh"),
    ("nga 3 vung tau",                             "ngã 3 vũng tàu"),
    ("bv cho ray",                                 "bệnh viện chợ rẫy"),
    ("Bv nhi đong",                                "bệnh viện nhi đồng"),
    ("benh vien 175",                              "bệnh viện 175"),
    ("dh kinh te tphcm",                           "đại học kinh tế thành phố hồ chí minh"),
    ("86 xo viet nghe tinh p19 binh thanh",        "86 xô viết nghệ tĩnh phường 19 bình thạnh"),
    ("duong le van viet q9",                       "đường lê văn việt quận 9"),
    ("hem 212 thoai ngoc hau phuong phu thanh",    "hẻm 212 thoại ngọc hầu phường phú thạnh"),
    ("kcn song than 1",                            "khu công nghiệp sóng thần 1"),
    ("ubnd xa phuoc thai",                         "ủy ban nhân dân xã phước thái"),
    ("158/16 binh quew",                           "158/16 bình quới"),
    ("chung cu ha",                                "chung cư hà"),
    ("ngã 6 tahnhf",                               "ngã 6 thành"),
    ("tttm aeon mall tan phu",                     "trung tâm thương mại aeon mall tân phú"),
    ("dh bach khoa ha noi",                        "đại học bách khoa hà nội"),
]
"""

BASELINES_CODE = """\
BASELINES = {
    "Arm A (2E1D d128)":  {"enc_dec": "2E/1D",  "params": "6.5M",  "p50": "2.38ms", "mean_acc": 63.50, "plasticity": 41.7, "retention": 70.2, "user_centric": 58.3, "protection_heldout": 56.8, "zc": "55.6%"},
    "Arm E (2E2D d128)":  {"enc_dec": "2E/2D",  "params": "7.1M",  "p50": "5.71ms", "mean_acc": 67.33, "plasticity": 43.6, "retention": 73.0, "user_centric": 66.7, "protection_heldout": 62.4, "zc": "50.0%"},
    "Arm B (4E4D d128)":  {"enc_dec": "4E/4D",  "params": "9.6M",  "p50": "5.51ms", "mean_acc": 67.11, "plasticity": 43.7, "retention": 74.2, "user_centric": 66.7, "protection_heldout": 61.0, "zc": "55.6%"},
    "Arm D (4E1D d128)":  {"enc_dec": "4E/1D",  "params": "7.7M",  "p50": "7.25ms", "mean_acc": 65.87, "plasticity": 42.4, "retention": 71.1, "user_centric": 66.7, "protection_heldout": 58.4, "zc": "61.1%"},
    "Arm F (2E1D d256)":  {"enc_dec": "2E/1D",  "params": "13.4M", "p50": "3.97ms", "mean_acc": 64.76, "plasticity": 42.4, "retention": 72.5, "user_centric": 58.3, "protection_heldout": 58.8, "zc": "61.1%"},
    "Arm C (6E6D d128)":  {"enc_dec": "6E/6D",  "params": "12.1M", "p50": "17.63ms","mean_acc": 64.23, "plasticity": 42.7, "retention": 72.8, "user_centric": 58.3, "protection_heldout": 59.6, "zc": "66.7%"},
    "Arm G (ViT5-base)":  {"enc_dec": "12E/12D","params": "226M",  "p50": "?ms",    "mean_acc": None,  "plasticity": None,"retention": None, "user_centric": None, "protection_heldout": None, "zc": "?%"},
}
"""


def generate_notebook():
    cells = []

    # ── 0. Header ─────────────────────────────────────────────────────────────
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# ReparoS Pilot Arm H — BARTpho-syllable-base Fine-Tuning & Benchmark\n",
            "### Fair Comparison: Pretrained Vietnamese BART (132M) vs Transformer Scratch (6–13M) vs ViT5 (226M)\n",
            "\n",
            "**Research Question:** Với cùng 300K pairs + 10K steps, pretraining style (T5 vs BART) và tokenizer (syllable BPE vs SPM)\n",
            "mang lại bao nhiêu lợi thế so với Transformer scratch?\n",
            "\n",
            "| Arm | Model | Params | Pretrained? | Tokenizer | Hypothesis |\n",
            "| :---: | :--- | :---: | :---: | :--- | :--- |\n",
            "| **A–F** | Transformer Scratch | 6–13M | ❌ | SPM 12k | Baseline architectural scaling |\n",
            "| **G** | ViT5-base | 226M | ✅ T5 | SPM (ViT5) | T5 pretraining advantage |\n",
            "| **H** | BARTpho-syllable-base | 132M | ✅ BART | Syllable BPE | BART denoising + syllable tokenizer |\n",
            "\n",
            "**Fair Comparison Contract:**\n",
            "- ✅ Cùng dataset: `data/base_v3_pilot` (300,000 pairs)\n",
            "- ✅ Cùng 10,000 steps\n",
            "- ✅ Cùng 5 frozen eval suites (3,100 queries)\n",
            "- ✅ Cùng 18 zero-click cases\n",
            "- ✅ CTranslate2 CPU INT8 inference (benchmark đồng nhất)\n",
        ]
    })

    # ── 1. Setup & Install ────────────────────────────────────────────────────
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os, sys, time, json, shutil, subprocess, math\n",
            "from pathlib import Path\n",
            "\n",
            "os.environ['TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD'] = '1'\n",
            "os.environ['HF_HUB_OFFLINE'] = '1'\n",
            "os.environ['TRANSFORMERS_OFFLINE'] = '1'\n",
            "os.environ['HF_DATASETS_OFFLINE'] = '1'\n",
            "os.environ['TOKENIZERS_PARALLELISM'] = 'false'\n",
            "\n",
            "WORKING = Path('/kaggle/working')\n",
            "KAGGLE_INPUT = Path('/kaggle/input')\n",
            "\n",
            "# ── Locate offline wheelhouse (same as Arm G notebook) ─────────────────\n",
            "WHEELS_DIR = Path('/kaggle/input/datasets/vanhieu1125/build-wheel/wheels')\n",
            "assert WHEELS_DIR.is_dir(), f'Missing offline wheelhouse: {WHEELS_DIR}'\n",
            "\n",
            "wheel_names = [p.name.lower().replace('-', '_') for p in WHEELS_DIR.glob('*.whl')]\n",
            "required = ('transformers_4.48.3', 'tokenizers_0.21.0', 'huggingface_hub_0.28.1',\n",
            "            'safetensors_0.5.2', 'accelerate_', 'sentencepiece_0.2.0', 'ctranslate2_4.6.2')\n",
            "missing = [r for r in required if not any(w.startswith(r) for w in wheel_names)]\n",
            "assert not missing, f'Missing wheels: {missing}'\n",
            "print(f'[+] Offline wheelhouse OK: {len(wheel_names)} wheels available')\n",
            "\n",
            "# Install into isolated dir to avoid Kaggle preloaded Transformers v5 conflicts\n",
            "RUNTIME_DIR = WORKING / 'arm-h-site-packages'\n",
            "if RUNTIME_DIR.exists():\n",
            "    shutil.rmtree(RUNTIME_DIR)\n",
            "RUNTIME_DIR.mkdir(parents=True)\n",
            "subprocess.run([\n",
            "    sys.executable, '-m', 'pip', 'install', '-q',\n",
            "    '--no-index', '--find-links', str(WHEELS_DIR),\n",
            "    '--no-deps', '--target', str(RUNTIME_DIR),\n",
            "    'transformers==4.48.3', 'tokenizers==0.21.0', 'huggingface_hub==0.28.1',\n",
            "    'safetensors==0.5.2', 'accelerate', 'sentencepiece==0.2.0', 'ctranslate2==4.6.2',\n",
            "], check=True)\n",
            "\n",
            "import importlib\n",
            "sys.path.insert(0, str(RUNTIME_DIR))\n",
            "for mod in list(sys.modules):\n",
            "    if mod.split('.', 1)[0] in {'transformers', 'huggingface_hub', 'accelerate'}:\n",
            "        del sys.modules[mod]\n",
            "importlib.invalidate_caches()\n",
            "\n",
            "import torch, transformers, ctranslate2\n",
            "assert transformers.__version__ == '4.48.3', transformers.__version__\n",
            "assert ctranslate2.__version__ == '4.6.2', ctranslate2.__version__\n",
            "assert torch.cuda.is_available(), 'CUDA GPU required'\n",
            "print(f'torch={torch.__version__} | transformers={transformers.__version__} | ctranslate2={ctranslate2.__version__}')\n",
            "print(f'GPU: {torch.cuda.get_device_name(0)} | VRAM: {torch.cuda.get_device_properties(0).total_memory/1e9:.2f} GB')\n",
        ]
    })

    # ── 2. Locate BARTpho snapshot + Dataset ─────────────────────────────────
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "from transformers import AutoTokenizer, AutoModelForSeq2SeqLM\n",
            "from torch.utils.data import Dataset\n",
            "\n",
            "MODEL_ID = 'vinai/bartpho-syllable-base'\n",
            "\n",
            "# BARTpho snapshot must be mounted as a separate Kaggle Dataset.\n",
            "# Valid snapshot: contains config.json, vocab.json, merges.txt, model weights.\n",
            "def is_bartpho_snapshot(path):\n",
            "    has_weights = any((path / n).exists() for n in\n",
            "        ('model.safetensors', 'pytorch_model.bin', 'model.safetensors.index.json'))\n",
            "    return ((path / 'config.json').exists() and\n",
            "            (path / 'vocab.json').exists() and\n",
            "            has_weights)\n",
            "\n",
            "# Scan /kaggle/input for the BARTpho snapshot\n",
            "MODEL_PATH = None\n",
            "for candidate in [\n",
            "    Path('/kaggle/input/datasets/vanhieu1125/bartpho-syllable-base/bartpho-syllable-base'),\n",
            "    Path('/kaggle/input/bartpho-syllable-base/bartpho-syllable-base'),\n",
            "    Path('/kaggle/input/bartpho-syllable/bartpho-syllable-base'),\n",
            "]:\n",
            "    if is_bartpho_snapshot(candidate):\n",
            "        MODEL_PATH = candidate\n",
            "        break\n",
            "\n",
            "if MODEL_PATH is None:\n",
            "    # Fallback: scan all of /kaggle/input for config.json + vocab.json\n",
            "    for p in KAGGLE_INPUT.rglob('config.json'):\n",
            "        d = p.parent\n",
            "        if is_bartpho_snapshot(d) and 'bartpho' in str(d).lower():\n",
            "            MODEL_PATH = d\n",
            "            break\n",
            "\n",
            "assert MODEL_PATH is not None, (\n",
            "    'BARTpho-syllable-base snapshot not found under /kaggle/input. '\n",
            "    'Please mount the dataset: vinai/bartpho-syllable-base'\n",
            ")\n",
            "print(f'[+] BARTpho snapshot found: {MODEL_PATH}')\n",
            "\n",
            "# Load tokenizer — BARTpho uses a RoBERTa-style BPE tokenizer with syllable segmentation\n",
            "tokenizer = AutoTokenizer.from_pretrained(str(MODEL_PATH), local_files_only=True, use_fast=False)\n",
            "print(f'[+] Tokenizer: {type(tokenizer).__name__} | Vocab size: {tokenizer.vocab_size}')\n",
            "\n",
            "# ── Locate pilot dataset ────────────────────────────────────────────────────\n",
            "pilot_dir = None\n",
            "for p in KAGGLE_INPUT.rglob('data/base_v3_pilot'):\n",
            "    if p.is_dir():\n",
            "        pilot_dir = p\n",
            "        break\n",
            "if pilot_dir is None:  # fallback: local repo\n",
            "    pilot_dir = Path('.').resolve() / 'data/base_v3_pilot'\n",
            "assert pilot_dir.exists(), f'Pilot dataset not found: {pilot_dir}'\n",
            "\n",
            "eval_dir = pilot_dir.parent / 'base_v3_eval'\n",
            "assert eval_dir.exists(), f'Eval dir not found: {eval_dir}'\n",
            "print(f'[+] Pilot dataset: {pilot_dir}')\n",
            "print(f'[+] Eval dir:      {eval_dir}')\n",
            "\n",
            "# ── Dataset class ────────────────────────────────────────────────────────────\n",
            "class QueryCorrectionDataset(Dataset):\n",
            "    def __init__(self, src_file, tgt_file, tokenizer, max_length=64):\n",
            "        srcs = [l.rstrip('\\r\\n') for l in open(src_file, encoding='utf-8')]\n",
            "        tgts = [l.rstrip('\\r\\n') for l in open(tgt_file, encoding='utf-8')]\n",
            "        assert len(srcs) == len(tgts)\n",
            "        pairs = [(s.strip().lower(), t.strip().lower()) for s, t in zip(srcs, tgts)]\n",
            "        assert all(s and t for s, t in pairs), 'Blank row found'\n",
            "        self.srcs = [s for s, _ in pairs]\n",
            "        self.tgts = [t for _, t in pairs]\n",
            "        self.tokenizer = tokenizer\n",
            "        self.max_length = max_length\n",
            "\n",
            "    def __len__(self): return len(self.srcs)\n",
            "\n",
            "    def __getitem__(self, idx):\n",
            "        enc = self.tokenizer(\n",
            "            self.srcs[idx], max_length=self.max_length,\n",
            "            padding='max_length', truncation=True, return_tensors='pt'\n",
            "        )\n",
            "        labels = self.tokenizer(\n",
            "            self.tgts[idx], max_length=self.max_length,\n",
            "            padding='max_length', truncation=True, return_tensors='pt'\n",
            "        )['input_ids'].squeeze(0)\n",
            "        labels[labels == self.tokenizer.pad_token_id] = -100\n",
            "        return {\n",
            "            'input_ids':      enc['input_ids'].squeeze(0),\n",
            "            'attention_mask': enc['attention_mask'].squeeze(0),\n",
            "            'labels':         labels,\n",
            "        }\n",
            "\n",
            "print('Loading train/valid datasets...')\n",
            "train_ds = QueryCorrectionDataset(pilot_dir / 'train.src', pilot_dir / 'train.tgt', tokenizer)\n",
            "valid_ds = QueryCorrectionDataset(pilot_dir / 'valid.src', pilot_dir / 'valid.tgt', tokenizer)\n",
            "assert len(train_ds) == 300_000, f'Expected 300k, got {len(train_ds):,}'\n",
            "assert len(valid_ds) == 5_000,   f'Expected 5k, got {len(valid_ds):,}'\n",
            "print(f'[+] Train: {len(train_ds):,} | Valid: {len(valid_ds):,}')\n",
        ]
    })

    # ── 3. Fine-Tuning ────────────────────────────────────────────────────────
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer\n",
            "\n",
            "OUTPUT_ROOT = WORKING / 'checkpoints/arm_h_bartpho_syllable'\n",
            "OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "print(f'Initializing {MODEL_ID} from {MODEL_PATH}...')\n",
            "model = AutoModelForSeq2SeqLM.from_pretrained(str(MODEL_PATH), local_files_only=True)\n",
            "total_params = sum(p.numel() for p in model.parameters())\n",
            "print(f'[+] {MODEL_ID} loaded! Total parameters: {total_params / 1e6:.2f}M')\n",
            "\n",
            "# ── Hyperparameters: matching Arm G fair comparison contract ───────────────\n",
            "# BARTpho-syllable is 132M vs ViT5-base 226M → can afford slightly larger batch\n",
            "eval_kwarg = 'eval_strategy' if hasattr(Seq2SeqTrainingArguments, 'eval_strategy') else 'evaluation_strategy'\n",
            "training_args = Seq2SeqTrainingArguments(\n",
            "    **{\n",
            "        eval_kwarg:                  'steps',\n",
            "        'output_dir':                str(OUTPUT_ROOT),\n",
            "        'max_steps':                 10_000,          # Fair: same as Arm G & Arms A-F\n",
            "        'per_device_train_batch_size': 64,\n",
            "        'per_device_eval_batch_size':  128,\n",
            "        'gradient_accumulation_steps': 1,\n",
            "        'learning_rate':             5e-5,\n",
            "        'warmup_steps':              500,\n",
            "        'weight_decay':              0.01,\n",
            "        'logging_steps':             200,\n",
            "        'save_steps':                5_000,\n",
            "        'save_total_limit':          2,\n",
            "        'eval_steps':                2_500,\n",
            "        'bf16':                      torch.cuda.is_available(),\n",
            "        'fp16':                      False,\n",
            "        'tf32':                      False,\n",
            "        'dataloader_num_workers':    4,\n",
            "        'report_to':                 'none',\n",
            "        'seed':                      2026,\n",
            "        'predict_with_generate':     False,\n",
            "    }\n",
            ")\n",
            "\n",
            "trainer = Seq2SeqTrainer(\n",
            "    model=model, args=training_args,\n",
            "    train_dataset=train_ds, eval_dataset=valid_ds,\n",
            "    tokenizer=tokenizer,\n",
            ")\n",
            "\n",
            "print('\\n' + '='*80)\n",
            "print('STARTING 10,000-STEP FINE-TUNING FOR PILOT ARM H (BARTpho-syllable-base)')\n",
            "print('='*80)\n",
            "t0 = time.time()\n",
            "trainer.train()\n",
            "dur = (time.time() - t0) / 60.0\n",
            "print(f'\\n[+] Training finished in {dur:.1f} minutes!')\n",
            "\n",
            "# Save final checkpoint\n",
            "step_10k_dir = OUTPUT_ROOT / 'checkpoint-10000'\n",
            "trainer.save_model(str(step_10k_dir))\n",
            "tokenizer.save_pretrained(str(step_10k_dir))\n",
            "print(f'[+] Saved step-10000 model to {step_10k_dir}')\n",
        ]
    })

    # ── 4. CTranslate2 Conversion ─────────────────────────────────────────────
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "CT2_DIR = OUTPUT_ROOT / 'ct2_model'\n",
            "if CT2_DIR.exists():\n",
            "    shutil.rmtree(CT2_DIR)\n",
            "\n",
            "print('\\n' + '='*80)\n",
            "print('CONVERTING BARTpho-syllable-base CHECKPOINT TO CTRANSLATE2 (FP16)')\n",
            "print('='*80)\n",
            "\n",
            "import ctranslate2.converters\n",
            "converter = ctranslate2.converters.TransformersConverter(str(step_10k_dir))\n",
            "converter.convert(str(CT2_DIR), quantization='float16', force=True)\n",
            "assert (CT2_DIR / 'model.bin').is_file(), f'Conversion failed: {CT2_DIR}'\n",
            "print(f'[+] CTranslate2 conversion OK: {CT2_DIR}')\n",
            "\n",
            "# Inspect converted config\n",
            "ct2_cfg = json.load(open(CT2_DIR / 'config.json', encoding='utf-8'))\n",
            "print(f'    CT2 config: {ct2_cfg}')\n",
        ]
    })

    # ── 5. Evaluation ─────────────────────────────────────────────────────────
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import ctranslate2\n",
            "\n",
            "print('\\n' + '='*80)\n",
            "print('EVALUATING ARM H ON 5 FROZEN SUITES & 18 ZERO-CLICK CASES')\n",
            "print('='*80)\n",
            "\n",
            "SUITES = {\n",
            "    'plasticity':         (eval_dir / 'plasticity.src',         eval_dir / 'plasticity.tgt'),\n",
            "    'retention':          (eval_dir / 'retention.src',          eval_dir / 'retention.tgt'),\n",
            "    'user_centric':       (eval_dir / 'user_centric.src',       eval_dir / 'user_centric.tgt'),\n",
            "    'protection_seen':    (eval_dir / 'protection_seen.src',    eval_dir / 'protection_seen.tgt'),\n",
            "    'protection_heldout': (eval_dir / 'protection_heldout.src', eval_dir / 'protection_heldout.tgt'),\n",
            "}\n",
            "for s, (src, tgt) in SUITES.items():\n",
            "    assert src.is_file() and tgt.is_file(), f'Missing suite: {s}'\n",
            "assert sum(sum(1 for l in open(s, encoding='utf-8') if l.strip())\n",
            "           for s, _ in SUITES.values()) == 3_100, 'Expected 3,100 queries in frozen suites'\n",
            "\n",
        ] + [line + "\n" for line in ZERO_CLICK_CASES_CODE.strip().splitlines()] + [
            "\n",
            "# Load CTranslate2 CPU INT8 Translator (identical benchmark setup to Arms A-F & G)\n",
            "translator_cpu = ctranslate2.Translator(str(CT2_DIR), device='cpu', compute_type='int8', intra_threads=4)\n",
            "\n",
            "# Warmup\n",
            "warm = tokenizer.tokenize('ha noi')\n",
            "translator_cpu.translate_batch([warm], beam_size=1)\n",
            "\n",
            "def predict_ct2(texts, beam_size=1, rep_penalty=1.2, batch_size=64):\n",
            "    preds = []\n",
            "    for i in range(0, len(texts), batch_size):\n",
            "        chunk = texts[i:i+batch_size]\n",
            "        # BARTpho tokenizer: tokenize() returns wordpiece/BPE tokens\n",
            "        token_batch = [tokenizer.tokenize(t.strip().lower()) for t in chunk]\n",
            "        outputs = translator_cpu.translate_batch(\n",
            "            token_batch, beam_size=beam_size, repetition_penalty=rep_penalty\n",
            "        )\n",
            "        for out in outputs:\n",
            "            hyp = out.hypotheses[0]\n",
            "            # Decode back: convert_tokens_to_ids then batch_decode\n",
            "            ids = tokenizer.convert_tokens_to_ids(hyp)\n",
            "            text = tokenizer.decode(ids, skip_special_tokens=True)\n",
            "            preds.append(text.strip().lower())\n",
            "    return preds\n",
            "\n",
            "def compute_acc(preds, tgts):\n",
            "    return sum(p.strip().lower() == t.strip().lower() for p, t in zip(preds, tgts)) / len(tgts) * 100.0\n",
            "\n",
            "# ── 5-Suite Evaluation ──────────────────────────────────────────────────────\n",
            "arm_h_results = {'name': 'Arm H (BARTpho-syllable-base)', 'params': f'{total_params/1e6:.1f}M',\n",
            "                 'suites': {}, 'latency': {}, 'zero_click_preds': {}}\n",
            "suite_accs = []\n",
            "for s_name, (src_p, tgt_p) in SUITES.items():\n",
            "    srcs = [l.strip() for l in open(src_p, 'r', encoding='utf-8') if l.strip()]\n",
            "    tgts = [l.strip() for l in open(tgt_p, 'r', encoding='utf-8') if l.strip()]\n",
            "    preds = predict_ct2(srcs, beam_size=1, rep_penalty=1.2)\n",
            "    acc = compute_acc(preds, tgts)\n",
            "    arm_h_results['suites'][s_name] = acc\n",
            "    suite_accs.append(acc)\n",
            "    print(f'  {s_name:<22}: {acc:6.2f}%  ({len(srcs):,} pairs)')\n",
            "\n",
            "mean_acc = sum(suite_accs) / len(suite_accs)\n",
            "arm_h_results['mean_acc'] = mean_acc\n",
            "print(f'\\n>> 5-SUITE MEAN ACCURACY (ARM H): {mean_acc:.2f}%')\n",
            "\n",
            "# ── Zero-Click Evaluation ───────────────────────────────────────────────────\n",
            "zc_srcs = [c[0] for c in ZERO_CLICK_CASES]\n",
            "zc_tgts = [c[1] for c in ZERO_CLICK_CASES]\n",
            "zc_b1  = predict_ct2(zc_srcs, beam_size=1,  rep_penalty=1.2)\n",
            "zc_b4  = predict_ct2(zc_srcs, beam_size=4,  rep_penalty=1.2)\n",
            "zc_b10 = predict_ct2(zc_srcs, beam_size=10, rep_penalty=1.2)\n",
            "zc_acc_b1  = compute_acc(zc_b1,  zc_tgts)\n",
            "zc_acc_b4  = compute_acc(zc_b4,  zc_tgts)\n",
            "zc_acc_b10 = compute_acc(zc_b10, zc_tgts)\n",
            "arm_h_results['zero_click_acc_beam1']  = zc_acc_b1\n",
            "arm_h_results['zero_click_acc_beam4']  = zc_acc_b4\n",
            "arm_h_results['zero_click_acc_beam10'] = zc_acc_b10\n",
            "arm_h_results['zero_click_preds'] = {s: p for s, p in zip(zc_srcs, zc_b1)}\n",
            "print(f'Zero-Click: Beam1={zc_acc_b1:.1f}% | Beam4={zc_acc_b4:.1f}% | Beam10={zc_acc_b10:.1f}%')\n",
        ]
    })

    # ── 6. Latency Profiling ──────────────────────────────────────────────────
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# CPU INT8 latency profiling — identical methodology to Arms A-F & G\n",
            "test_queries = [\n",
            "    'dh bach khoa ha noi',\n",
            "    '86 xo viet nghe tinh p19 binh thanh',\n",
            "    'bv cho ray',\n",
            "    'duong le van viet q9',\n",
            "    'kcn song than 1',\n",
            "]\n",
            "\n",
            "for beam in (1, 4):\n",
            "    lats = []\n",
            "    for q in test_queries * 20:\n",
            "        toks = tokenizer.tokenize(q)\n",
            "        t0 = time.perf_counter()\n",
            "        translator_cpu.translate_batch([toks], beam_size=beam, repetition_penalty=1.2)\n",
            "        lats.append((time.perf_counter() - t0) * 1000.0)\n",
            "    lats.sort()\n",
            "    p50 = lats[len(lats) // 2]\n",
            "    p90 = lats[int(len(lats) * 0.9)]\n",
            "    arm_h_results['latency'][f'cpu_p50_beam{beam}_ms'] = p50\n",
            "    arm_h_results['latency'][f'cpu_p90_beam{beam}_ms'] = p90\n",
            "    print(f'Beam {beam}: P50={p50:.2f}ms | P90={p90:.2f}ms')\n",
        ]
    })

    # ── 7. Comparison Table & Report ──────────────────────────────────────────
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
        ] + [line + "\n" for line in BASELINES_CODE.strip().splitlines()] + [
            "\n",
            "h = arm_h_results\n",
            "g_s = h['suites']\n",
            "h_p50 = f\"{h['latency']['cpu_p50_beam1_ms']:.2f}ms\"\n",
            "h_mean = h['mean_acc']\n",
            "\n",
            "lines = []\n",
            "lines.append('# Báo Cáo Đối Sánh: Pilot Arm H (BARTpho-syllable-base) vs Arms A–G')\n",
            "lines.append('')\n",
            "lines.append('So sánh sòng phẳng: 300K pairs, 10K steps, CPU INT8, cùng 5 suites + 18 zero-click.')\n",
            "lines.append('')\n",
            "lines.append('## Bảng Tổng Hợp')\n",
            "lines.append('| Arm | Kiến trúc | Params | Pretrained | CPU P50 | Mean Acc | Plasticity | Retention | User-Centric | Prot-Heldout | ZC (B1) |')\n",
            "lines.append('| :--- | :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |')\n",
            "for arm_name, d in BASELINES.items():\n",
            "    ma = f\"{d['mean_acc']:.2f}%\" if d['mean_acc'] else '?'\n",
            "    pl = f\"{d['plasticity']:.1f}%\" if d['plasticity'] else '?'\n",
            "    re = f\"{d['retention']:.1f}%\" if d['retention'] else '?'\n",
            "    uc = f\"{d['user_centric']:.1f}%\" if d['user_centric'] else '?'\n",
            "    ph = f\"{d['protection_heldout']:.1f}%\" if d['protection_heldout'] else '?'\n",
            "    pretrained = '✅ ViT5' if 'ViT5' in arm_name else '❌ Scratch'\n",
            "    lines.append(f\"| **{arm_name}** | {d['enc_dec']} | {d['params']} | {pretrained} | {d['p50']} | **{ma}** | {pl} | {re} | {uc} | {ph} | {d['zc']} |\")\n",
            "\n",
            "lines.append(f\"| **Arm H (BARTpho-syllable)** | 6E/6D BART | {h['params']} | ✅ BART | {h_p50} | **{h_mean:.2f}%** | {g_s.get('plasticity',0):.1f}% | {g_s.get('retention',0):.1f}% | {g_s.get('user_centric',0):.1f}% | {g_s.get('protection_heldout',0):.1f}% | {h['zero_click_acc_beam1']:.1f}% |\")\n",
            "\n",
            "lines.append('')\n",
            "lines.append('## Phân Tích')\n",
            "delta_vs_a = h_mean - 63.50\n",
            "delta_vs_g = h_mean - (BASELINES['Arm G (ViT5-base)']['mean_acc'] or 0)\n",
            "lines.append(f'- **vs Arm A (scratch baseline):** {delta_vs_a:+.2f}%')\n",
            "lines.append(f'- **vs Arm G (ViT5-base):** {delta_vs_g:+.2f}%  (BARTpho BART-style vs T5-style pretraining)')\n",
            "lines.append(f'- **Latency:** {h_p50} vs Arm A 2.38ms (Arm A {(h[\"latency\"][\"cpu_p50_beam1_ms\"]/2.38):.1f}x faster)')\n",
            "\n",
            "lines.append('')\n",
            "lines.append('## Zero-Click Detail (18 cases, Beam 1)')\n",
            "lines.append('| Input | Expected | Arm H Pred | Status |')\n",
            "lines.append('| :--- | :--- | :--- | :---: |')\n",
            "for q, exp in ZERO_CLICK_CASES:\n",
            "    p = h['zero_click_preds'].get(q, '')\n",
            "    st = '✅' if p.strip().lower() == exp.strip().lower() else '❌'\n",
            "    lines.append(f'| `{q}` | **{exp}** | `{p}` | {st} |')\n",
            "\n",
            "report_text = '\\n'.join(lines) + '\\n'\n",
            "report_file = WORKING / 'scaling_laws_report_arm_h.md'\n",
            "results_json = WORKING / 'benchmark_results_arm_h.json'\n",
            "\n",
            "with open(report_file, 'w', encoding='utf-8') as f:\n",
            "    f.write(report_text)\n",
            "with open(results_json, 'w', encoding='utf-8') as f:\n",
            "    json.dump(h, f, indent=2, ensure_ascii=False)\n",
            "\n",
            "print(report_text)\n",
            "print(f'\\n[+] Saved: {report_file}')\n",
            "print(f'[+] Saved: {results_json}')\n",
        ]
    })

    # ── Assemble notebook ─────────────────────────────────────────────────────
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 4,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10.0"},
        },
        "cells": cells,
    }
    return notebook


if __name__ == "__main__":
    nb = generate_notebook()
    out_path = Path("notebook/benchmark_arm_h_bartpho_kaggle.ipynb")
    out_path.parent.mkdir(exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print(f"[+] Notebook saved: {out_path}")
    print(f"    Cells: {len(nb['cells'])}")
