"""Fit a small logistic model for gold-exact confidence of each top-10 candidate.

Input is generated by build_reparos_base_v3_confidence_data.py. The model
predicts strict gold agreement on the three diagnostic suites, not semantic
correctness or a production-calibrated probability.

Run:
    .venv/Scripts/python.exe scripts/train_reparos_candidate_confidence.py
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import unicodedata
from difflib import SequenceMatcher
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "artifacts/reparos_base_v3_confidence_14088/top10_predictions.jsonl"
DEFAULT_OUTPUT = ROOT / "artifacts/reparos_base_v3_confidence_14088/logistic_confidence_v3_margin"
FEATURE_NAMES = (
    "sequence_score",
    "gap_from_top_score",
    "top1_top2_margin",
    "character_change_ratio",
    "relative_length_change",
    "unchanged_input",
    "input_length",
) + tuple(f"rank_{rank}" for rank in range(1, 11))
CALIBRATION_FEATURE_NAMES = ("base_logit", "rank_2", "rank_3_to_5", "rank_6_to_10")
SPLIT_NAMES = ("train", "calibration", "test")


def normalized(value: str) -> str:
    return " ".join(unicodedata.normalize("NFC", value).split())


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def split_of(expected: str, seed: int, calibration_fraction: float, test_fraction: float) -> int:
    # Same canonical target stays on one side even across benchmark suites.
    group = normalized(expected)
    digest = hashlib.sha256(f"{seed}\0{group}".encode("utf-8")).digest()
    value = int.from_bytes(digest[:8], "big") / 2**64
    if value < test_fraction:
        return 2
    if value < test_fraction + calibration_fraction:
        return 1
    return 0


def features(
    query: str, hypothesis: str, score: float, top_score: float, top1_top2_margin: float, rank: int
) -> list[float]:
    query_n = normalized(query)
    hypothesis_n = normalized(hypothesis)
    length = max(len(query_n), 1)
    return [
        score,
        top_score - score,
        top1_top2_margin,
        1.0 - SequenceMatcher(None, query_n, hypothesis_n, autojunk=False).ratio(),
        (len(hypothesis_n) - len(query_n)) / length,
        float(query_n == hypothesis_n),
        float(len(query_n)),
    ] + [float(rank == candidate_rank) for candidate_rank in range(1, 11)]


def load_rows(
    path: Path, seed: int, calibration_fraction: float, test_fraction: float
) -> tuple[list[dict], np.ndarray, np.ndarray, np.ndarray]:
    queries: list[dict] = []
    feature_rows: list[list[float]] = []
    labels: list[int] = []
    splits: list[int] = []
    seen: set[tuple[str, str]] = set()
    with path.open("r", encoding="utf-8") as stream:
        for line_number, line in enumerate(stream, 1):
            if not line.strip():
                continue
            row = json.loads(line)
            identity = (row["suite"], row["query_id"])
            if identity in seen:
                raise ValueError(f"duplicate query at line {line_number}: {identity}")
            seen.add(identity)
            hypotheses = row["hypotheses"]
            scores = row["sequence_scores"]
            given_labels = row["strict_exact_labels"]
            if len(hypotheses) != len(scores) or len(scores) != 10 or len(given_labels) != 10:
                raise ValueError(f"expected 10 aligned hypotheses, scores, labels at line {line_number}")
            split = split_of(row["expected"], seed, calibration_fraction, test_fraction)
            correct = normalized(row["expected"])
            for rank, (hypothesis, score, label) in enumerate(zip(hypotheses, scores, given_labels), 1):
                verified = int(normalized(hypothesis) == correct)
                if label != verified or label not in (0, 1):
                    raise ValueError(f"label mismatch at line {line_number}, rank {rank}")
                feature_rows.append(features(
                    row["input"], hypothesis, float(score), float(scores[0]),
                    float(scores[0]) - float(scores[1]), rank,
                ))
                labels.append(label)
                splits.append(split)
            queries.append(row)
    if not queries:
        raise ValueError(f"no query rows in {path}")
    return (
        queries,
        np.asarray(feature_rows, dtype=np.float64),
        np.asarray(labels, dtype=np.float64),
        np.asarray(splits, dtype=np.int8),
    )


def objective(x: np.ndarray, y: np.ndarray, params: np.ndarray, l2: float) -> float:
    logits = x @ params
    return float(np.mean(np.logaddexp(0.0, logits) - y * logits) + l2 * np.dot(params[1:], params[1:]) / 2)


def fit_logistic(x: np.ndarray, y: np.ndarray, l2: float, max_iterations: int) -> tuple[np.ndarray, int]:
    """Damped Newton optimization; intercept is not regularized."""
    params = np.zeros(x.shape[1], dtype=np.float64)
    prevalence = float(np.clip(y.mean(), 1e-6, 1 - 1e-6))
    params[0] = math.log(prevalence / (1 - prevalence))
    regularizer = np.eye(x.shape[1], dtype=np.float64) * l2
    regularizer[0, 0] = 0.0
    count = len(y)
    for iteration in range(1, max_iterations + 1):
        logits = np.clip(x @ params, -40, 40)
        probabilities = 1 / (1 + np.exp(-logits))
        gradient = (x.T @ (probabilities - y)) / count + regularizer @ params
        curvature = probabilities * (1 - probabilities)
        hessian = (x.T @ (x * curvature[:, None])) / count + regularizer
        step = np.linalg.solve(hessian, gradient)
        if np.max(np.abs(step)) < 1e-7:
            return params, iteration - 1
        previous_loss = objective(x, y, params, l2)
        rate = 1.0
        while rate >= 1 / 1024 and objective(x, y, params - rate * step, l2) > previous_loss + 1e-12:
            rate /= 2
        if rate < 1 / 1024:
            if np.max(np.abs(gradient)) < 1e-6:
                return params, iteration - 1
            raise RuntimeError("logistic optimization failed to find a descending step")
        params -= rate * step
        if np.max(np.abs(rate * step)) < 1e-7:
            return params, iteration
    return params, max_iterations


def calibration_design(base_logits: np.ndarray, ranks: np.ndarray) -> np.ndarray:
    return np.column_stack((
        np.ones(len(base_logits)),
        base_logits,
        (ranks == 2).astype(np.float64),
        ((ranks >= 3) & (ranks <= 5)).astype(np.float64),
        (ranks >= 6).astype(np.float64),
    ))


def sigmoid(logits: np.ndarray) -> np.ndarray:
    values = np.clip(logits, -40, 40)
    return 1 / (1 + np.exp(-values))


def summary(probabilities: np.ndarray, labels: np.ndarray) -> dict:
    if len(labels) == 0:
        return {"candidates": 0}
    clipped = np.clip(probabilities, 1e-12, 1 - 1e-12)
    bins = []
    for index in range(10):
        lower, upper = index / 10, (index + 1) / 10
        inside = (probabilities >= lower) & (probabilities < upper if index < 9 else probabilities <= upper)
        bins.append({
            "range": [lower, upper],
            "count": int(inside.sum()),
            "mean_confidence": float(probabilities[inside].mean()) if inside.any() else None,
            "observed_exact_rate": float(labels[inside].mean()) if inside.any() else None,
        })
    return {
        "candidates": len(labels),
        "positive_candidates": int(labels.sum()),
        "positive_rate": float(labels.mean()),
        "brier_score": float(np.mean((probabilities - labels) ** 2)),
        "log_loss": float(np.mean(-labels * np.log(clipped) - (1 - labels) * np.log1p(-clipped))),
        "mean_confidence": float(probabilities.mean()),
        "calibration_bins": bins,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--calibration-fraction", type=float, default=0.15)
    parser.add_argument("--test-fraction", type=float, default=0.15)
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument("--l2", type=float, default=1e-3)
    parser.add_argument("--max-iterations", type=int, default=40)
    args = parser.parse_args()
    if (
        args.calibration_fraction <= 0 or args.test_fraction <= 0
        or args.calibration_fraction + args.test_fraction >= 1
        or args.l2 <= 0 or args.max_iterations < 1
    ):
        parser.error("calibration/test fractions must be positive with sum below 1; l2 and max iterations must be positive")
    input_path = args.input.resolve()
    queries, raw_features, labels, splits = load_rows(
        input_path, args.seed, args.calibration_fraction, args.test_fraction
    )
    train_mask, calibration_mask, test_mask = (splits == value for value in range(3))
    if any(not mask.any() or len(set(labels[mask])) != 2 for mask in (train_mask, calibration_mask, test_mask)):
        raise ValueError("train, calibration, and test must each contain both labels")
    mean = raw_features[train_mask].mean(axis=0)
    scale = raw_features[train_mask].std(axis=0)
    scale[scale == 0] = 1
    standardized = (raw_features - mean) / scale
    design = np.column_stack((np.ones(len(labels)), standardized))
    params, iterations = fit_logistic(design[train_mask], labels[train_mask], args.l2, args.max_iterations)
    base_logits = design @ params
    base_probabilities = sigmoid(base_logits)
    ranks = np.tile(np.arange(1, 11), len(queries))
    calibrator_design = calibration_design(base_logits, ranks)
    calibration_params, calibration_iterations = fit_logistic(
        calibrator_design[calibration_mask], labels[calibration_mask], args.l2, args.max_iterations
    )
    calibrated_trial = sigmoid(calibrator_design @ calibration_params)
    # The optional second stage is reported, but the base logistic model is
    # the default output until an independent evaluation supports using it.
    probabilities = base_probabilities

    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    model = {
        "schema_version": 2,
        "task": "predict strict gold-exact label for each ReparoS top-10 candidate",
        "feature_names": FEATURE_NAMES,
        "feature_mean": mean.tolist(),
        "feature_scale": scale.tolist(),
        "intercept": float(params[0]),
        "coefficients": params[1:].tolist(),
        "l2": args.l2,
        "iterations": iterations,
        "input": str(input_path),
        "input_sha256": sha256(input_path),
        "calibrator": {
            "feature_names": CALIBRATION_FEATURE_NAMES,
            "intercept": float(calibration_params[0]),
            "coefficients": calibration_params[1:].tolist(),
            "iterations": calibration_iterations,
            "status": "experimental; not used for confidence_gold_exact output",
        },
        "output_model": "base_logistic_with_rank_indicators",
        "split": "SHA256(seed + NFC/whitespace-normalized expected); all 10 candidates of a query share a train/calibration/test split",
        "seed": args.seed,
        "calibration_fraction": args.calibration_fraction,
        "test_fraction": args.test_fraction,
        "label_limitation": "Gold-exact is a proxy; alternative correct rewrites may be labeled 0. Diagnostic data is not production traffic.",
    }
    (output / "model.json").write_text(json.dumps(model, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    with (output / "top10_with_confidence.jsonl").open("w", encoding="utf-8") as stream:
        for index, query in enumerate(queries):
            start = index * 10
            record = {
                "suite": query["suite"],
                "query_id": query["query_id"],
                "input": query["input"],
                "expected": query["expected"],
                "split": SPLIT_NAMES[int(splits[start])],
                "hypotheses": query["hypotheses"],
                "sequence_scores": query["sequence_scores"],
                "strict_exact_labels": query["strict_exact_labels"],
                "confidence_gold_exact": probabilities[start : start + 10].tolist(),
                "confidence_after_calibration_trial": calibrated_trial[start : start + 10].tolist(),
            }
            stream.write(json.dumps(record, ensure_ascii=False) + "\n")

    report = {
        "queries": len(queries),
        "train_queries": int(train_mask.sum() // 10),
        "calibration_queries": int(calibration_mask.sum() // 10),
        "test_queries": int(test_mask.sum() // 10),
        "train_base": summary(base_probabilities[train_mask], labels[train_mask]),
        "calibration_base": summary(base_probabilities[calibration_mask], labels[calibration_mask]),
        "calibration_calibrated": summary(calibrated_trial[calibration_mask], labels[calibration_mask]),
        "test_base": summary(base_probabilities[test_mask], labels[test_mask]),
        "test_calibrated": summary(calibrated_trial[test_mask], labels[test_mask]),
        "test_by_suite": {},
        "test_by_rank": {},
    }
    suites = np.repeat(np.asarray([query["suite"] for query in queries], dtype=object), 10)
    for suite in sorted(set(suites)):
        mask = test_mask & (suites == suite)
        report["test_by_suite"][suite] = summary(probabilities[mask], labels[mask])
    for rank in range(1, 11):
        mask = test_mask & (ranks == rank)
        report["test_by_rank"][str(rank)] = summary(probabilities[mask], labels[mask])
    (output / "report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(
        f"Train {report['train_queries']} queries; calibration {report['calibration_queries']}; "
        f"untouched test {report['test_queries']}"
    )
    print(
        f"Test Brier base={report['test_base']['brier_score']:.4f}, "
        f"calibration trial={report['test_calibrated']['brier_score']:.4f}; "
        f"log loss base={report['test_base']['log_loss']:.4f}, "
        f"calibration trial={report['test_calibrated']['log_loss']:.4f}"
    )
    print(f"Saved model, report, and top-10 confidence rows to {output}")


if __name__ == "__main__":
    main()
